name: pokemon_api
description: "A new Flutter project."
publish_to: 'none' # Remove esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ãcones estilo iOS
  cupertino_icons: ^1.0.8

  # HTTP para consumo de API
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Regras de lint recomendadas
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Exemplo de como adicionar imagens ao projeto
  # assets:
  #   - assets/images/

  # Exemplo de como adicionar fontes personalizadas
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
